on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "printing path"
        run: pwd
      - name: "printing name"
        run: echo mohamed

      - uses: actions/checkout@v3 
      - name: "printing fils"
        run: ls
